  apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
  kind: BigQueryJob
  metadata:
    name: cymbal-mock-load-job
    annotations:
      configsync.gke.io/cluster-name-selector: cymbal-admin
  spec:
    location: "US"
    jobTimeoutMs: "600000"
    load:
      sourceUris:
        - "gs://krm-test-5-datasets/cymbal-mock-transactions.csv"
      destinationTable:
        tableRef:
          name: cymbalmocktable
      sourceFormat: "CSV"
      encoding: "UTF-8"
      fieldDelimiter: ","
      quote: '"'
      allowQuotedNewlines: false
      maxBadRecords: 0
      allowJaggedRows: false
      ignoreUnknownValues: false
      skipLeadingRows: 1
      autodetect: true
      writeDisposition: "WRITE_APPEND"
      schemaUpdateOptions:
        - "ALLOW_FIELD_ADDITION"
        - "ALLOW_FIELD_RELAXATION"
---
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: cymbalmockdataset
  annotations:
    configsync.gke.io/cluster-name-selector: cymbal-admin
spec:
  friendlyName: cymbal-mock-dataset
---
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: cymbalmocktable
  annotations:
    configsync.gke.io/cluster-name-selector: cymbal-admin
spec:
  friendlyName: cymbal-mock-table
  datasetRef:
    name: cymbalmockdataset