apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: cymbal-prod
  sourceFormat: unstructured
  policyController:
    enabled: true
  git:
    syncRepo: https://github.com/askmeegs/cymbalbank-policy
    syncBranch: main
    secretType: none
    policyDir: "/"