name: Pull Request CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: rojopolis/spellcheck-github-actions@0.14.0
        name: Spellcheck
        with:
          config_path: .github/workflows/spellcheck.yaml