name: Pull Request CI
on:
  pull_request:
    branches:
      - main
jobs:
  PR-Spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - uses: rojopolis/spellcheck-github-actions@0.14.0
        name: Spellcheck